//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tamin.Registration.Utility.SmsioService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ArrayOfString", Namespace="Send", ItemName="string")]
    [System.SerializableAttribute()]
    public class ArrayOfString : System.Collections.Generic.List<string> {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ArrayOfLong", Namespace="Send", ItemName="long")]
    [System.SerializableAttribute()]
    public class ArrayOfLong : System.Collections.Generic.List<long> {
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="Send", ConfigurationName="SmsioService.SendSoap")]
    public interface SendSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="Send/SendSms", ReplyAction="*")]
        Tamin.Registration.Utility.SmsioService.SendSmsResponse SendSms(Tamin.Registration.Utility.SmsioService.SendSmsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="Send/SendSms", ReplyAction="*")]
        System.Threading.Tasks.Task<Tamin.Registration.Utility.SmsioService.SendSmsResponse> SendSmsAsync(Tamin.Registration.Utility.SmsioService.SendSmsRequest request);
        
        // CODEGEN: Generating message contract since element name username from namespace Send is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="Send/Credit", ReplyAction="*")]
        Tamin.Registration.Utility.SmsioService.CreditResponse Credit(Tamin.Registration.Utility.SmsioService.CreditRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="Send/Credit", ReplyAction="*")]
        System.Threading.Tasks.Task<Tamin.Registration.Utility.SmsioService.CreditResponse> CreditAsync(Tamin.Registration.Utility.SmsioService.CreditRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="Send/Delivery", ReplyAction="*")]
        int Delivery(long recId);
        
        [System.ServiceModel.OperationContractAttribute(Action="Send/Delivery", ReplyAction="*")]
        System.Threading.Tasks.Task<int> DeliveryAsync(long recId);
        
        // CODEGEN: Generating message contract since element name username from namespace Send is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="Send/GetInbox", ReplyAction="*")]
        Tamin.Registration.Utility.SmsioService.GetInboxResponse GetInbox(Tamin.Registration.Utility.SmsioService.GetInboxRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="Send/GetInbox", ReplyAction="*")]
        System.Threading.Tasks.Task<Tamin.Registration.Utility.SmsioService.GetInboxResponse> GetInboxAsync(Tamin.Registration.Utility.SmsioService.GetInboxRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SendSmsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SendSms", Namespace="Send", Order=0)]
        public Tamin.Registration.Utility.SmsioService.SendSmsRequestBody Body;
        
        public SendSmsRequest() {
        }
        
        public SendSmsRequest(Tamin.Registration.Utility.SmsioService.SendSmsRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="Send")]
    public partial class SendSmsRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string username;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string password;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string from;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public Tamin.Registration.Utility.SmsioService.ArrayOfString to;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string text;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=5)]
        public bool flash;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public byte[] status;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public Tamin.Registration.Utility.SmsioService.ArrayOfLong recId;
        
        public SendSmsRequestBody() {
        }
        
        public SendSmsRequestBody(string username, string password, string from, Tamin.Registration.Utility.SmsioService.ArrayOfString to, string text, bool flash, byte[] status, Tamin.Registration.Utility.SmsioService.ArrayOfLong recId) {
            this.username = username;
            this.password = password;
            this.from = from;
            this.to = to;
            this.text = text;
            this.flash = flash;
            this.status = status;
            this.recId = recId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SendSmsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SendSmsResponse", Namespace="Send", Order=0)]
        public Tamin.Registration.Utility.SmsioService.SendSmsResponseBody Body;
        
        public SendSmsResponse() {
        }
        
        public SendSmsResponse(Tamin.Registration.Utility.SmsioService.SendSmsResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="Send")]
    public partial class SendSmsResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int SendSmsResult;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public byte[] status;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public Tamin.Registration.Utility.SmsioService.ArrayOfLong recId;
        
        public SendSmsResponseBody() {
        }
        
        public SendSmsResponseBody(int SendSmsResult, byte[] status, Tamin.Registration.Utility.SmsioService.ArrayOfLong recId) {
            this.SendSmsResult = SendSmsResult;
            this.status = status;
            this.recId = recId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CreditRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Credit", Namespace="Send", Order=0)]
        public Tamin.Registration.Utility.SmsioService.CreditRequestBody Body;
        
        public CreditRequest() {
        }
        
        public CreditRequest(Tamin.Registration.Utility.SmsioService.CreditRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="Send")]
    public partial class CreditRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string username;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string password;
        
        public CreditRequestBody() {
        }
        
        public CreditRequestBody(string username, string password) {
            this.username = username;
            this.password = password;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CreditResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CreditResponse", Namespace="Send", Order=0)]
        public Tamin.Registration.Utility.SmsioService.CreditResponseBody Body;
        
        public CreditResponse() {
        }
        
        public CreditResponse(Tamin.Registration.Utility.SmsioService.CreditResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="Send")]
    public partial class CreditResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public double CreditResult;
        
        public CreditResponseBody() {
        }
        
        public CreditResponseBody(double CreditResult) {
            this.CreditResult = CreditResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetInboxRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetInbox", Namespace="Send", Order=0)]
        public Tamin.Registration.Utility.SmsioService.GetInboxRequestBody Body;
        
        public GetInboxRequest() {
        }
        
        public GetInboxRequest(Tamin.Registration.Utility.SmsioService.GetInboxRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="Send")]
    public partial class GetInboxRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string username;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string password;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string to;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public int year;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public int month;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=5)]
        public int day;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=6)]
        public int hour;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=7)]
        public int minute;
        
        public GetInboxRequestBody() {
        }
        
        public GetInboxRequestBody(string username, string password, string to, int year, int month, int day, int hour, int minute) {
            this.username = username;
            this.password = password;
            this.to = to;
            this.year = year;
            this.month = month;
            this.day = day;
            this.hour = hour;
            this.minute = minute;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetInboxResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetInboxResponse", Namespace="Send", Order=0)]
        public Tamin.Registration.Utility.SmsioService.GetInboxResponseBody Body;
        
        public GetInboxResponse() {
        }
        
        public GetInboxResponse(Tamin.Registration.Utility.SmsioService.GetInboxResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="Send")]
    public partial class GetInboxResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Tamin.Registration.Utility.SmsioService.ArrayOfString GetInboxResult;
        
        public GetInboxResponseBody() {
        }
        
        public GetInboxResponseBody(Tamin.Registration.Utility.SmsioService.ArrayOfString GetInboxResult) {
            this.GetInboxResult = GetInboxResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface SendSoapChannel : Tamin.Registration.Utility.SmsioService.SendSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SendSoapClient : System.ServiceModel.ClientBase<Tamin.Registration.Utility.SmsioService.SendSoap>, Tamin.Registration.Utility.SmsioService.SendSoap {
        
        public SendSoapClient() {
        }
        
        public SendSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SendSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SendSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SendSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Tamin.Registration.Utility.SmsioService.SendSmsResponse Tamin.Registration.Utility.SmsioService.SendSoap.SendSms(Tamin.Registration.Utility.SmsioService.SendSmsRequest request) {
            return base.Channel.SendSms(request);
        }
        
        public int SendSms(string username, string password, string from, Tamin.Registration.Utility.SmsioService.ArrayOfString to, string text, bool flash, ref byte[] status, ref Tamin.Registration.Utility.SmsioService.ArrayOfLong recId) {
            Tamin.Registration.Utility.SmsioService.SendSmsRequest inValue = new Tamin.Registration.Utility.SmsioService.SendSmsRequest();
            inValue.Body = new Tamin.Registration.Utility.SmsioService.SendSmsRequestBody();
            inValue.Body.username = username;
            inValue.Body.password = password;
            inValue.Body.from = from;
            inValue.Body.to = to;
            inValue.Body.text = text;
            inValue.Body.flash = flash;
            inValue.Body.status = status;
            inValue.Body.recId = recId;
            Tamin.Registration.Utility.SmsioService.SendSmsResponse retVal = ((Tamin.Registration.Utility.SmsioService.SendSoap)(this)).SendSms(inValue);
            status = retVal.Body.status;
            recId = retVal.Body.recId;
            return retVal.Body.SendSmsResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Tamin.Registration.Utility.SmsioService.SendSmsResponse> Tamin.Registration.Utility.SmsioService.SendSoap.SendSmsAsync(Tamin.Registration.Utility.SmsioService.SendSmsRequest request) {
            return base.Channel.SendSmsAsync(request);
        }
        
        public System.Threading.Tasks.Task<Tamin.Registration.Utility.SmsioService.SendSmsResponse> SendSmsAsync(string username, string password, string from, Tamin.Registration.Utility.SmsioService.ArrayOfString to, string text, bool flash, byte[] status, Tamin.Registration.Utility.SmsioService.ArrayOfLong recId) {
            Tamin.Registration.Utility.SmsioService.SendSmsRequest inValue = new Tamin.Registration.Utility.SmsioService.SendSmsRequest();
            inValue.Body = new Tamin.Registration.Utility.SmsioService.SendSmsRequestBody();
            inValue.Body.username = username;
            inValue.Body.password = password;
            inValue.Body.from = from;
            inValue.Body.to = to;
            inValue.Body.text = text;
            inValue.Body.flash = flash;
            inValue.Body.status = status;
            inValue.Body.recId = recId;
            return ((Tamin.Registration.Utility.SmsioService.SendSoap)(this)).SendSmsAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Tamin.Registration.Utility.SmsioService.CreditResponse Tamin.Registration.Utility.SmsioService.SendSoap.Credit(Tamin.Registration.Utility.SmsioService.CreditRequest request) {
            return base.Channel.Credit(request);
        }
        
        public double Credit(string username, string password) {
            Tamin.Registration.Utility.SmsioService.CreditRequest inValue = new Tamin.Registration.Utility.SmsioService.CreditRequest();
            inValue.Body = new Tamin.Registration.Utility.SmsioService.CreditRequestBody();
            inValue.Body.username = username;
            inValue.Body.password = password;
            Tamin.Registration.Utility.SmsioService.CreditResponse retVal = ((Tamin.Registration.Utility.SmsioService.SendSoap)(this)).Credit(inValue);
            return retVal.Body.CreditResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Tamin.Registration.Utility.SmsioService.CreditResponse> Tamin.Registration.Utility.SmsioService.SendSoap.CreditAsync(Tamin.Registration.Utility.SmsioService.CreditRequest request) {
            return base.Channel.CreditAsync(request);
        }
        
        public System.Threading.Tasks.Task<Tamin.Registration.Utility.SmsioService.CreditResponse> CreditAsync(string username, string password) {
            Tamin.Registration.Utility.SmsioService.CreditRequest inValue = new Tamin.Registration.Utility.SmsioService.CreditRequest();
            inValue.Body = new Tamin.Registration.Utility.SmsioService.CreditRequestBody();
            inValue.Body.username = username;
            inValue.Body.password = password;
            return ((Tamin.Registration.Utility.SmsioService.SendSoap)(this)).CreditAsync(inValue);
        }
        
        public int Delivery(long recId) {
            return base.Channel.Delivery(recId);
        }
        
        public System.Threading.Tasks.Task<int> DeliveryAsync(long recId) {
            return base.Channel.DeliveryAsync(recId);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Tamin.Registration.Utility.SmsioService.GetInboxResponse Tamin.Registration.Utility.SmsioService.SendSoap.GetInbox(Tamin.Registration.Utility.SmsioService.GetInboxRequest request) {
            return base.Channel.GetInbox(request);
        }
        
        public Tamin.Registration.Utility.SmsioService.ArrayOfString GetInbox(string username, string password, string to, int year, int month, int day, int hour, int minute) {
            Tamin.Registration.Utility.SmsioService.GetInboxRequest inValue = new Tamin.Registration.Utility.SmsioService.GetInboxRequest();
            inValue.Body = new Tamin.Registration.Utility.SmsioService.GetInboxRequestBody();
            inValue.Body.username = username;
            inValue.Body.password = password;
            inValue.Body.to = to;
            inValue.Body.year = year;
            inValue.Body.month = month;
            inValue.Body.day = day;
            inValue.Body.hour = hour;
            inValue.Body.minute = minute;
            Tamin.Registration.Utility.SmsioService.GetInboxResponse retVal = ((Tamin.Registration.Utility.SmsioService.SendSoap)(this)).GetInbox(inValue);
            return retVal.Body.GetInboxResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Tamin.Registration.Utility.SmsioService.GetInboxResponse> Tamin.Registration.Utility.SmsioService.SendSoap.GetInboxAsync(Tamin.Registration.Utility.SmsioService.GetInboxRequest request) {
            return base.Channel.GetInboxAsync(request);
        }
        
        public System.Threading.Tasks.Task<Tamin.Registration.Utility.SmsioService.GetInboxResponse> GetInboxAsync(string username, string password, string to, int year, int month, int day, int hour, int minute) {
            Tamin.Registration.Utility.SmsioService.GetInboxRequest inValue = new Tamin.Registration.Utility.SmsioService.GetInboxRequest();
            inValue.Body = new Tamin.Registration.Utility.SmsioService.GetInboxRequestBody();
            inValue.Body.username = username;
            inValue.Body.password = password;
            inValue.Body.to = to;
            inValue.Body.year = year;
            inValue.Body.month = month;
            inValue.Body.day = day;
            inValue.Body.hour = hour;
            inValue.Body.minute = minute;
            return ((Tamin.Registration.Utility.SmsioService.SendSoap)(this)).GetInboxAsync(inValue);
        }
    }
}
