// <auto-generated />
namespace Tamin.Registration.DataLayer.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class removemajor : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(removemajor));
        
        string IMigrationMetadata.Id
        {
            get { return "201908102123340_remove-major"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
